### ISSUE TITLE
Unable to build this fun little proj

### ISSUE THREAD

**Issue by O-J1** [kenwilcox/BlyncLight#1]
Hey Ken

Bit of a noob but was wanting to have a little play around with this and after spending a good 3hrs looking for a solution, I still seem unable to build this project.

What do you reccomended building this project with and how did you do it?

Thanks in advance, if you get back to me and sorry if this is sort of necroing it

**Comment by kenwilcox** [comment]
The ReadMe states that I was messing with the BlyncLight SDK. Did you download it?
I don't know if they changed it at all, but I have still have version 1.0.0.1 and it builds and runs.
What error(s) were you getting?
I no longer have Blync light

**Comment by kenwilcox** [comment]
I just downloaded and tried it with version 0.3.0.11 (so much for semver - the zip file states 3.0.3) and it build fine as well - I downloaded it from here: https://www.embrava.com/pages/embrava-software-sdk

**Comment by O-J1** [comment]
Thanks Ken 👍
